

/**
 *
 */
public abstract class Reservation {


    /**
     * Account number that the reservation belongs to.
     */
    protected String accountNumber;
    /**
     * Reservation number generated by UI. (10 characters)
     */
    protected String reservationNumber;
    /**
     * Lodging's physical address.
     */
    protected String physicalAddress;
    /**
     * Lodging's mailing address
     */
    protected String mailingAddress;
    /**
     * When the reservation starts  (Date or Calendar)
     */
    protected String reservationStartDate;
    /**
     * How many nights the reservation is
     */
    protected int numberOfNights;
    /**
     * How many beds are availible at the lodging.  (default 2)
     */
    protected int numberOfBeds = 2;
    /**
     * Number of bedrooms at the lodging. (default 1)
     */
    protected int numberOfBedrooms = 1;
    /**
     * Number of bathrooms at the lodging. (default 1)
     */
    protected int numberOfBathrooms = 1;
    /**
     * Lodging size in square feet. (integer)
     */
    protected int lodgingSize;
    /**
     * The total price of the reservation.
     */
    protected int priceOfReservation;


    /**
     * Reservation status (draft, completed, or cancelled)
     */
    protected String reservationStatus = "draft";


    //constructor with default values without passing values
    public Reservation(String reservationNumber, String reservationStatus) {
        this.accountNumber = "-99";
        this.reservationNumber = reservationNumber;
        this.reservationStatus = "draft";
        this.priceOfReservation = 0;
    }

    //2nd constructor with more attributes
    public Reservation(String accountNumber, String reservationNumber, String physicalAddress, String mailingAddress, String reservationStartDate,
                       int numberOfNights, int numberOfBeds, int numberOfBedrooms, int numberOfBathrooms, int lodgingSize, int priceOfReservation, String reservationStatus) {
        this.accountNumber = accountNumber;
        this.reservationNumber = reservationNumber;
        this.physicalAddress = physicalAddress;
        this.mailingAddress = mailingAddress;
        this.reservationStartDate = reservationStartDate;
        this.numberOfNights = numberOfNights;
    }

    // third constructor to parse variables from reading file
    public Reservation(String line) {
        // parse all variables. Use the Account constructor as an example
        accountNumber = line.substring(line.indexOf("<accountNumber>") + 15, line.indexOf("</accountNumber>"));
        reservationNumber = line.substring(line.indexOf("<reservationNumber>") + 19, line.indexOf("</reservationNumber>"));
        physicalAddress = line.substring(line.indexOf("<physicalAddress>") + 17, line.indexOf("</physicalAddress>"));
        mailingAddress = line.substring(line.indexOf("<mailingAddress>") + 16, line.indexOf("</mailingAddress>"));
        reservationStartDate = line.substring(line.indexOf("<reservationStartDate>") + 22, line.indexOf("</reservationStartDate>"));
        numberOfNights = Integer.parseInt(line.substring(line.indexOf(("<numberOfNights>") + 16, line.indexOf("</numberOfNights>"))));
        numberOfBeds = Integer.parseInt(line.substring(line.indexOf(("<numberOfBeds>") + 14, line.indexOf("</numberOfBeds>"))));
        numberOfBedrooms = Integer.parseInt(line.substring(line.indexOf(("<numberOfBedrooms>") + 18, line.indexOf("</numberOfBedrooms>"))));
        numberOfBathrooms = Integer.parseInt(line.substring(line.indexOf(("<numberOfBathrooms>") + 19, line.indexOf("</numberOfBathrooms>"))));
        lodgingSize = Integer.parseInt(line.substring(line.indexOf(("<lodgingSize>") + 13, line.indexOf("</lodgingSize>"))));
        priceOfReservation = Integer.parseInt(line.substring(line.indexOf(("<priceOfReservation>") + 20, line.indexOf("</priceOfReservation>"))));
        reservationStatus = line.substring(line.indexOf("<reservationStatus>") + 19, line.indexOf("</reservationStatus>"));

    }

    protected Reservation() {
    }


    //Save reservation information to a file
    public void saveToFile(String File) {
    }

    //Read reservation information from a file
    public void readFromFile(String File) {
    }


    /**
     * Setter for reservationStartDate
     */
    public void setReservationStartDate(String reservationStartDate) {
        this.reservationStartDate = reservationStartDate;
    }


    /**
     * Setter for numberOfNights
     */
    public void setNumberOfNights(int numberOfNights) {
        this.numberOfNights = numberOfNights;
    }


    /**
     * Setter for numberOfBeds
     */
    public void setNumberOfBeds(int numberOfBeds) {
        this.numberOfBeds = numberOfBeds;
    }


    /**
     * Setter for numberOfBedrooms
     */
    public void setNumberOfBedrooms(int numberOfBedrooms) {
        this.numberOfBedrooms = numberOfBedrooms;
    }

    /**
     * Setter for numberOfBathrooms
     */
    public void setNumberOfBathrooms(int numberOfBathrooms) {
        this.numberOfBathrooms = numberOfBathrooms;
    }

    /**
     * Setter for lodgingSize
     */
    public void setLodgingSize(int lodgingSize) {
        this.lodgingSize = lodgingSize;
    }

    /**
     * Setter for priceOfReservation
     */
    public void setPriceOfReservation(int priceOfReservation) {
        this.priceOfReservation = priceOfReservation;
    }

    /**
     * Setter for reservationStatus
     */
    public void setReservationStatus(String reservationStatus) {
        this.reservationStatus = reservationStatus;
    }

    /**
     * Setter for reservationNumber
     */
    public void setReservationNumber(String reservationNumber) {
        this.reservationNumber = reservationNumber;
    }

    /**
     * Setter for physicalAddress
     */
    public void setPhysicalAddress(String physicalAddress) {
        this.physicalAddress = physicalAddress;
    }

    /**
     * Setter for mailingAddress
     */
    public void setMailingAddress(String mailingAddress) {
        if (mailingAddress == null) {
            this.mailingAddress = physicalAddress;
        } else {
            this.mailingAddress = mailingAddress;
        }
    }


    /**
     * Getter for reservationStartDate
     */
    public String getReservationStartDate() {
        return reservationStartDate;
    }


    /**
     * Getter for numberOfNights
     */
    public int getNumberOfNights() {
        return numberOfNights;
    }


    /**
     * Getter for numberOfBeds
     */
    public int getNumberOfBeds() {
        return numberOfBeds;
    }

    /**
     * Getter for numberOfBedrooms
     */
    public int getNumberOfBedrooms() {
        return numberOfBedrooms;
    }

    /**
     * Getter for numberOfBathrooms
     */
    public int getNumberOfBathrooms() {
        return numberOfBathrooms;
    }

    /**
     * Getter for lodgingSize
     */
    public int getLodgingSize() {
        return lodgingSize;
    }

    /**
     * Getter for priceOfReservation
     */
    public int getPriceOfReservation() {
        return priceOfReservation;
    }

    /**
     * Getter for physicalAddress
     */
    public String getPhysicalAddress() {
        return physicalAddress;
    }

    /**
     * Getter for mailingAddress
     */
    public String getMailingAddress() {
        return mailingAddress;
    }

    /**
     * Getter for reservationStatus
     */
    public String getReservationStatus() {
        return reservationStatus;
    }

    /**
     * Output the class’s data to the screen.   toString() method
     *
     * @return Returns reservation's information.
     */
    public String showData() {
        /*
         * validate parameters
         * create a String array of an Reservation's data
         * print String
         */
        return null;
    }
}